name: Build and release
defaults:
  run:
    shell: bash -eo pipefail {0}

env:
  VK_APP_ID: ${{ secrets.VK_APP_ID }}
  VK_APP_SECRET: ${{ secrets.VK_APP_SECRET }}

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:


jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Prepare for build
        run: |
          rm -f vkoptions.py
          python vkoptions-ci-writer.py
      
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the build
        run: |
          python -m nuitka --assume-yes-for-downloads --onefile VkOrdnung.py -o VkOrdnung.exe
      
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: VkOrdnung.exe
          fail_on_unmatched_files: true
  
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Prepare for build
        run: |
          rm -f vkoptions.py
          python vkoptions-ci-writer.py
      
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the build
        run: |
          python -m nuitka --assume-yes-for-downloads --onefile VkOrdnung.py -o VkOrdnung.bin
      
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: VkOrdnung.bin
          fail_on_unmatched_files: true
